# Generated by Django 4.2.1 on 2024-06-27 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='experimentNumber',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
