# Generated by Django 4.2.1 on 2024-06-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_input_answers_answer1_answers_answer2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='participantGender',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
