# Generated by Django 4.2.1 on 2024-06-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_answers_participantgender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='participantGender',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
