# Generated by Django 4.2.1 on 2024-06-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_answers_answer5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='answer5',
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer1',
            field=models.CharField(default='No Answer', max_length=250),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer2',
            field=models.CharField(default='No Answer', max_length=250),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer3',
            field=models.CharField(default='No Answer', max_length=250),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer4',
            field=models.CharField(default='No Answer', max_length=250),
        ),
        migrations.AlterField(
            model_name='answers',
            name='participantName',
            field=models.CharField(max_length=20),
        ),
    ]
