# Generated by Django 4.2.1 on 2024-06-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_remove_answers_answer5_alter_answers_answer1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='participantName',
            field=models.CharField(default='Mustermann', max_length=20),
        ),
    ]
