# Generated by Django 4.2.1 on 2024-06-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_answers_participantname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='participantName',
            new_name='participant_Name',
        ),
    ]
