# Generated by Django 4.2.1 on 2024-06-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_rename_participantname_answers_participant_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='participant_Name',
            new_name='participantName',
        ),
    ]
