# Generated by Django 4.2.1 on 2024-06-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_rename_participant_name_answers_participantname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='participantName',
            field=models.CharField(max_length=20),
        ),
    ]
