# Generated by Django 4.2.1 on 2024-07-10 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_answers_participantname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 10, 19, 8, 28, 934633, tzinfo=datetime.timezone.utc)),
        ),
    ]
