# Generated by Django 4.2.1 on 2024-07-10 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_alter_answers_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 10, 20, 30, 37, 284814, tzinfo=datetime.timezone.utc)),
        ),
    ]
