# Generated by Django 4.2.1 on 2024-07-11 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_alter_answers_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answer2_pdf',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
