# Generated by Django 4.2.1 on 2024-07-11 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_answers_answer2_pdf_alter_answers_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 14, 57, 17, 233215, tzinfo=datetime.timezone.utc)),
        ),
    ]
