# Generated by Django 4.2.1 on 2024-07-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_alter_answers_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='answer2_pdf',
            new_name='pdf_clicked',
        ),
    ]
