# Generated by Django 4.2.1 on 2024-07-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_rename_answer2_pdf_answers_pdf_clicked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='participantGender',
            field=models.CharField(default='UnknownGender', max_length=20),
        ),
        migrations.AlterField(
            model_name='answers',
            name='participantName',
            field=models.CharField(default='UnknownName', max_length=20),
        ),
    ]
