# Generated by Django 4.2.1 on 2024-07-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_alter_answers_participantgender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='installed_update',
            field=models.IntegerField(default=0),
        ),
    ]
