# Generated by Django 4.2.14 on 2024-08-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_answers_installed_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='session_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer1',
            field=models.CharField(default='No Answer', max_length=500),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer2',
            field=models.CharField(default='No Answer', max_length=500),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer3',
            field=models.CharField(default='No Answer', max_length=500),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer4',
            field=models.CharField(default='No Answer', max_length=500),
        ),
    ]
