# Generated by Django 4.2.14 on 2024-08-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_answers_session_id_alter_answers_answer1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
