# Generated by Django 4.2.14 on 2024-08-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_alter_answers_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='survey_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
